== 익명 게시판

=== 전체 게시글 목록 조회(Offset)
operation::post/find-all-posts-by-offset[snippets='http-request,http-response,cookie,request-parameters,response-fields']

=== 게시글 목록 조회(Cursor)
operation::post/find-posts-by-cursor[snippets='http-request,http-response,cookie,request-parameters,response-fields']

=== 게시글 목록 조회(Offset)
operation::post/find-posts-by-offset[snippets='http-request,http-response,cookie,request-parameters,response-fields']

=== 게시글 상세 보기(실명)
operation::post/find-post-anonymity-false[snippets='http-request,http-response,cookie,path-parameters,response-fields']

=== 게시글 상세 보기(익명)
operation::post/find-post-anonymity-true[snippets='http-request,http-response,cookie,path-parameters,response-fields']

=== 게시글 검색(Cursor)
operation::post/search-posts-by-cursor[snippets='http-request,http-response,cookie,request-parameters,response-fields']

=== 게시글 검색(Offset)
operation::post/search-posts-by-offset[snippets='http-request,http-response,cookie,request-parameters,response-fields']

=== 게시글 작성
operation::post/write-post[snippets='http-request,http-response,cookie,request-parameters,request-fields,response-fields']

=== 게시글 수정
operation::post/update-post[snippets='http-request,http-response,cookie,path-parameters,request-fields,response-fields']

=== 게시글 삭제
operation::post/delete-post[snippets='http-request,http-response,cookie,path-parameters,response-fields']

=== 게시글 좋아요
operation::post/like-post[snippets='http-request,http-response,cookie,path-parameters,response-fields']

=== 게시글 스크랩
operation::post/scrap-post[snippets='http-request,http-response,cookie,path-parameters,response-fields']

=== Hot 게시글 목록 조회(Cursor)
operation::post/find-hot-posts-by-cursor[snippets='http-request,http-response,cookie,request-parameters,response-fields']

=== Hot 게시글 목록 조회(Offset)
operation::post/find-hot-posts-by-offset[snippets='http-request,http-response,cookie,request-parameters,response-fields']

=== Hot 게시글 검색(Cursor)
operation::post/search-hot-posts-by-cursor[snippets='http-request,http-response,cookie,request-parameters,response-fields']

=== Hot 게시글 검색(Offset)
operation::post/search-hot-posts-by-offset[snippets='http-request,http-response,cookie,request-parameters,response-fields']

=== 나의 게시글 목록 조회(Cursor)
operation::post/find-my-posts-by-cursor[snippets='http-request,http-response,cookie,request-parameters,response-fields']

=== 나의 게시글 목록 조회(Offset)
operation::post/find-my-posts-by-offset[snippets='http-request,http-response,cookie,request-parameters,response-fields']

=== 나의 스크랩 게시글 목록 조회(Cursor)
operation::post/find-my-scrap-posts-by-cursor[snippets='http-request,http-response,cookie,request-parameters,response-fields']

=== 나의 스크랩 게시글 목록 조회(Offset)
operation::post/find-my-scrap-posts-by-offset[snippets='http-request,http-response,cookie,request-parameters,response-fields']