== 리크루트


=== 리크루트 등록
operation::recruit/saveRecruit[snippets='http-request,request-fields,cookie,http-response,response-fields']


=== 리크루트 스크랩 토글
operation::recruit/toggleRecruitScrap[snippets='http-request,cookie,path-parameters,http-response,response-fields']


=== 리크루트 완료
operation::recruit/expiredRecruit[snippets='http-request,cookie,path-parameters,http-response,response-fields']


=== 리크루트 상세 조회
operation::recruit/detail[snippets='http-request,cookie,path-parameters,http-response,response-fields']


=== 리크루트 업데이트
operation::recruit/updateRecruit[snippets='http-request,cookie,path-parameters,request-fields,http-response,response-fields']


=== 리크루트 삭제
operation::recruit/deleteRecruit[snippets='http-request,cookie,path-parameters,http-response,response-fields']

=== 리크루트 목록 조회(Cursor)
operation::recruit/recruits-cursor[snippets='http-request,request-parameters,http-response,response-fields']

=== 리크루트 목록 조회(Offset)
operation::recruit/recruits-page[snippets='http-request,request-parameters,http-response,response-fields']

=== 사용자 지원 리크루트 목록 조회
operation::recruit/applied-recruits[snippets='http-request,cookie,request-parameters,http-response,response-fields']

=== 사용자 참여중 리크루트 목록 조회
operation::recruit/joined[snippets='http-request,cookie,request-parameters,http-response,response-fields']

=== 사용자 스크랩 리크루팅 목록 조회
operation::recruit/my-scrap[snippets='http-request,cookie,request-parameters,http-response,response-fields']